import React, { useState, useEffect } from 'react';
import { Navigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import axios from 'axios';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  FiUsers,
  FiDownload,
  FiSearch,
  FiFilter,
  FiEye,
  FiRefreshCw,
  FiFileText,
  FiBook,
  FiBarChart2,
  FiCalendar,
  FiX
} from 'react-icons/fi';
import './AuditorDashboard.css';

const AuditorDashboard = () => {
  const { user, isAuthenticated } = useAuth();
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedRole, setSelectedRole] = useState('all');
  const [selectedUser, setSelectedUser] = useState(null);
  const [showModal, setShowModal] = useState(false);
  const [pdfGenerating, setPdfGenerating] = useState(false);

  const API_BASE_URL = 'http://localhost:5001/api';

  useEffect(() => {
    fetchUsers();
  }, []);

  // Check if user is auditor
  if (!isAuthenticated || user?.role !== 'auditor') {
    return <Navigate to="/login" replace />;
  }

  const fetchUsers = async () => {
    try {
      setLoading(true);
      const response = await axios.get(`${API_BASE_URL}/users/admin/users`, {
        headers: { Authorization: `Bearer ${localStorage.getItem('token')}` }
      });

      if (response.data.success) {
        setUsers(response.data.data);
      }
    } catch (error) {
      console.error('Error fetching users:', error);
      setError('Failed to fetch users. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const calculateUserProgress = (user) => {
    if (!user.enrolledCourses || user.enrolledCourses.length === 0) {
      return { totalCourses: 0, averageProgress: 0, completedCourses: 0 };
    }

    let totalProgress = 0;
    let completedCourses = 0;
    let validCoursesCount = 0;

    user.enrolledCourses.forEach(enrollment => {
      const course = enrollment.course;
      
      // Skip enrollments with null courses
      if (!course) return;
      
      validCoursesCount++;
      const progress = enrollment.progress || {};
      
      const totalContent = (course.lecturePages?.length || 0) + (course.quizzes?.length || 0);
      const completedContent = (progress.completedPages?.length || 0) + 
                              (progress.completedQuizzes?.length || 0);
      
      const courseProgress = totalContent > 0 ? (completedContent / totalContent) * 100 : 0;
      totalProgress += courseProgress;
      
      if (courseProgress === 100) {
        completedCourses++;
      }
    });

    return {
      totalCourses: validCoursesCount,
      averageProgress: validCoursesCount > 0 ? totalProgress / validCoursesCount : 0,
      completedCourses
    };
  };

  const getQuizScores = (user) => {
    const scores = [];
    
    user.enrolledCourses?.forEach(enrollment => {
      // Skip enrollments with null courses
      if (!enrollment.course) return;
      
      const progress = enrollment.progress || {};
      const completedQuizzes = progress.completedQuizzes || [];
      
      completedQuizzes.forEach(quiz => {
        scores.push({
          courseName: enrollment.course.courseName,
          score: quiz.score || 0,
          completedAt: quiz.completedAt
        });
      });
    });

    return scores.sort((a, b) => new Date(b.completedAt) - new Date(a.completedAt));
  };

  const generatePDFReport = async () => {
    setPdfGenerating(true);
    
    try {
      console.log('Generating auditor PDF report...');
      
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.width;
      const pageHeight = doc.internal.pageSize.height;
      
      // Header with styling
      doc.setFillColor(139, 69, 19); // Brown color for auditor
      doc.rect(0, 0, pageWidth, 30, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('PolicyPulse Learning - Audit Report', 14, 20);
      
      // Report metadata
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 14, 40);
      doc.text(`Generated by: ${user?.name || 'Auditor'} (Auditor)`, 14, 46);
      doc.text(`Total Records: ${users.length} users`, 14, 52);
      
      let yPosition = 65;

      // Summary Statistics Section
      doc.setFillColor(245, 245, 220); // Light beige for auditor theme
      doc.rect(14, yPosition - 5, pageWidth - 28, 35, 'F');
      
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 0);
      doc.text('User Statistics Summary', 18, yPosition + 5);
      
      const totalUsers = users.length;
      const adminUsers = users.filter(u => u.role === 'admin').length;
      const studentUsers = users.filter(u => u.role === 'employee').length;
      const instructorUsers = users.filter(u => u.role === 'instructor').length;
      const securityManagerUsers = users.filter(u => u.role === 'securitymanager').length;
      const auditorUsers = users.filter(u => u.role === 'auditor').length;
      const activeUsers = users.filter(u => u.isActive).length;
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`Total Users: ${totalUsers}`, 18, yPosition + 15);
      doc.text(`Active Users: ${activeUsers}`, 18, yPosition + 22);
      doc.text(`Employees: ${studentUsers}`, 80, yPosition + 15);
      doc.text(`Instructors: ${instructorUsers}`, 80, yPosition + 22);
      doc.text(`Administrators: ${adminUsers}`, 130, yPosition + 15);
      doc.text(`Security Managers: ${securityManagerUsers}`, 130, yPosition + 22);
      doc.text(`Auditors: ${auditorUsers}`, 18, yPosition + 29);
      
      yPosition += 45;

      // Prepare user table data
      console.log('Processing user data for audit report...');
      const tableData = users.map((userData, index) => {
        console.log(`Processing user ${index + 1}: ${userData.name}`);
        
        try {
          const progress = calculateUserProgress(userData);
          const quizScores = getQuizScores(userData);
          const avgQuizScore = quizScores.length > 0 
            ? (quizScores.reduce((sum, score) => sum + score.score, 0) / quizScores.length).toFixed(1)
            : 'N/A';
          
          return [
            userData.name || 'N/A',
            userData.email || 'N/A',
            (userData.role || 'N/A').charAt(0).toUpperCase() + (userData.role || 'N/A').slice(1),
            userData.isActive ? 'Active' : 'Inactive',
            progress.totalCourses.toString(),
            `${progress.averageProgress.toFixed(1)}%`,
            progress.completedCourses.toString(),
            avgQuizScore,
            userData.createdAt ? new Date(userData.createdAt).toLocaleDateString() : 'N/A'
          ];
        } catch (userError) {
          console.error(`Error processing user ${userData.name}:`, userError);
          return [
            userData.name || 'N/A',
            userData.email || 'N/A',
            (userData.role || 'N/A').charAt(0).toUpperCase() + (userData.role || 'N/A').slice(1),
            userData.isActive ? 'Active' : 'Inactive',
            '0',
            '0%',
            '0',
            'N/A',
            userData.createdAt ? new Date(userData.createdAt).toLocaleDateString() : 'N/A'
          ];
        }
      });

      console.log('Creating audit table...');
      
      // User Details Table
      autoTable(doc, {
        head: [['Name', 'Email', 'Role', 'Status', 'Enrolled', 'Avg Progress', 'Completed', 'Quiz Avg', 'Joined']],
        body: tableData,
        startY: yPosition,
        theme: 'striped',
        headStyles: {
          fillColor: [139, 69, 19], // Brown theme for auditor
          textColor: 255,
          fontSize: 9,
          fontStyle: 'bold',
          halign: 'center'
        },
        bodyStyles: {
          fontSize: 8,
          cellPadding: 2,
          valign: 'middle'
        },
        columnStyles: {
          0: { cellWidth: 22, halign: 'left' },   // Name
          1: { cellWidth: 32, halign: 'left' },   // Email
          2: { cellWidth: 18, halign: 'center' }, // Role
          3: { cellWidth: 16, halign: 'center' }, // Status
          4: { cellWidth: 16, halign: 'center' }, // Enrolled
          5: { cellWidth: 18, halign: 'center' }, // Progress
          6: { cellWidth: 16, halign: 'center' }, // Completed
          7: { cellWidth: 16, halign: 'center' }, // Quiz Score
          8: { cellWidth: 18, halign: 'center' }  // Joined
        },
        margin: { left: 14, right: 14 },
        alternateRowStyles: {
          fillColor: [252, 248, 227] // Light beige alternating rows
        },
        didDrawPage: function (data) {
          // Page footer
          doc.setFontSize(8);
          doc.setTextColor(128);
          const pageNumber = doc.internal.getNumberOfPages();
          doc.text(
            `Page ${data.pageNumber} of ${pageNumber}`,
            pageWidth - 25,
            pageHeight - 10
          );
          doc.text(
            'PolicyPulse Learning Management System - Audit Report',
            14,
            pageHeight - 10
          );
        }
      });

      // Save the PDF with timestamp
      const timestamp = new Date().toISOString().split('T')[0];
      const fileName = `PolicyPulse_Audit_Report_${timestamp}.pdf`;
      console.log('Saving audit PDF report as:', fileName);
      doc.save(fileName);
      
      console.log('✅ Audit PDF report generated successfully!');
      setError(''); // Clear any previous errors
      
    } catch (error) {
      console.error('❌ Error generating audit PDF:', error);
      setError(`Failed to generate PDF report: ${error.message}`);
    } finally {
      setPdfGenerating(false);
    }
  };

  const filteredUsers = users.filter(user => {
    const matchesSearch = user.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         user.email.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesRole = selectedRole === 'all' || user.role === selectedRole;
    return matchesSearch && matchesRole;
  });

  const handleViewUser = (user) => {
    setSelectedUser(user);
    setShowModal(true);
  };

  if (loading) {
    return (
      <div className="auditor-dashboard">
        <div className="loading-container">
          <div className="loading-spinner"></div>
          <p>Loading user data...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="auditor-dashboard">
      <div className="dashboard-header">
        <div className="header-content">
          <h1>
            <FiFileText className="header-icon" />
            Auditor Dashboard
          </h1>
          <p>Read-only access to user management and system audit</p>
        </div>
      </div>

      {error && (
        <div className="error-message">
          <p>{error}</p>
          <button onClick={() => setError('')} className="close-error">
            <FiX />
          </button>
        </div>
      )}

      {/* Statistics Cards */}
      <div className="stats-container">
        <div className="stat-card">
          <FiUsers className="stat-icon" />
          <div className="stat-info">
            <h3>{users.length}</h3>
            <p>Total Users</p>
          </div>
        </div>
        
        <div className="stat-card">
          <FiBarChart2 className="stat-icon" />
          <div className="stat-info">
            <h3>{users.filter(u => u.role === 'employee').length}</h3>
            <p>Employees</p>
          </div>
        </div>
        
        <div className="stat-card">
          <FiBook className="stat-icon" />
          <div className="stat-info">
            <h3>{users.filter(u => u.role === 'instructor').length}</h3>
            <p>Instructors</p>
          </div>
        </div>
        
        <div className="stat-card">
          <FiFileText className="stat-icon" />
          <div className="stat-info">
            <h3>{users.filter(u => u.isActive).length}</h3>
            <p>Active Users</p>
          </div>
        </div>
      </div>

      {/* Controls */}
      <div className="controls-section">
        <div className="controls-left">
          <div className="search-box">
            <FiSearch className="search-icon" />
            <input
              type="text"
              placeholder="Search users..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          
          <div className="filter-dropdown">
            <FiFilter className="filter-icon" />
            <select 
              value={selectedRole} 
              onChange={(e) => setSelectedRole(e.target.value)}
            >
              <option value="all">All Roles</option>
              <option value="employee">Employees</option>
              <option value="instructor">Instructors</option>
              <option value="admin">Administrators</option>
              <option value="securitymanager">Security Managers</option>
              <option value="auditor">Auditors</option>
            </select>
          </div>
        </div>
        
        <div className="controls-right">
          <button 
            onClick={generatePDFReport}
            className="btn-export"
            disabled={pdfGenerating}
          >
            <FiDownload />
            {pdfGenerating ? 'Generating...' : 'Export Audit Report'}
          </button>
          
          <button onClick={() => fetchUsers()} className="btn-refresh">
            <FiRefreshCw />
            Refresh
          </button>
        </div>
      </div>

      {/* Users Table */}
      <div className="table-container">
        <table className="users-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>Status</th>
              <th>Enrolled Courses</th>
              <th>Progress</th>
              <th>Quiz Performance</th>
              <th>Joined</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredUsers.map(user => {
              const progress = calculateUserProgress(user);
              const quizScores = getQuizScores(user);
              const avgQuizScore = quizScores.length > 0 
                ? (quizScores.reduce((sum, score) => sum + score.score, 0) / quizScores.length).toFixed(1)
                : 'N/A';
              
              return (
                <tr key={user._id}>
                  <td>
                    <div className="user-info">
                      <strong>{user.name}</strong>
                    </div>
                  </td>
                  <td>{user.email}</td>
                  <td>
                    <span className={`role-badge ${user.role}`}>
                      {user.role.charAt(0).toUpperCase() + user.role.slice(1)}
                    </span>
                  </td>
                  <td>
                    <span className={`status-badge ${user.isActive ? 'active' : 'inactive'}`}>
                      {user.isActive ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td>{progress.totalCourses}</td>
                  <td>
                    <div className="progress-info">
                      <span>{progress.averageProgress.toFixed(1)}%</span>
                      <div className="progress-bar">
                        <div 
                          className="progress-fill" 
                          style={{width: `${Math.min(progress.averageProgress, 100)}%`}}
                        ></div>
                      </div>
                    </div>
                  </td>
                  <td>{avgQuizScore}</td>
                  <td>{new Date(user.createdAt).toLocaleDateString()}</td>
                  <td>
                    <div className="actions">
                      <button 
                        onClick={() => handleViewUser(user)}
                        className="btn-view"
                        title="View Details"
                      >
                        <FiEye />
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* User Details Modal */}
      {showModal && selectedUser && (
        <div className="modal-overlay">
          <div className="modal-content">
            <div className="modal-header">
              <h2>User Details (Read-Only)</h2>
              <button 
                onClick={() => setShowModal(false)}
                className="modal-close"
              >
                <FiX />
              </button>
            </div>
            
            <div className="modal-body">
              <div className="user-details-grid">
                <div className="detail-section">
                  <h3>Basic Information</h3>
                  <div className="detail-item">
                    <label>Name:</label>
                    <span>{selectedUser.name}</span>
                  </div>
                  <div className="detail-item">
                    <label>Email:</label>
                    <span>{selectedUser.email}</span>
                  </div>
                  <div className="detail-item">
                    <label>Role:</label>
                    <span className={`role-badge ${selectedUser.role}`}>
                      {selectedUser.role.charAt(0).toUpperCase() + selectedUser.role.slice(1)}
                    </span>
                  </div>
                  <div className="detail-item">
                    <label>Status:</label>
                    <span className={`status-badge ${selectedUser.isActive ? 'active' : 'inactive'}`}>
                      {selectedUser.isActive ? 'Active' : 'Inactive'}
                    </span>
                  </div>
                  <div className="detail-item">
                    <label>Joined:</label>
                    <span>{new Date(selectedUser.createdAt).toLocaleDateString()}</span>
                  </div>
                </div>

                <div className="detail-section">
                  <h3>Course Progress</h3>
                  {selectedUser.enrolledCourses && selectedUser.enrolledCourses.length > 0 ? (
                    <div className="courses-list">
                      {selectedUser.enrolledCourses.map((enrollment, index) => (
                        <div key={index} className="course-item">
                          <h4>{enrollment.course?.courseName || 'Course Name Unavailable'}</h4>
                          <p>Enrolled: {new Date(enrollment.enrolledAt).toLocaleDateString()}</p>
                          <p>Status: {enrollment.isCompleted ? 'Completed' : 'In Progress'}</p>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p>No courses enrolled</p>
                  )}
                </div>

                <div className="detail-section">
                  <h3>Quiz Performance</h3>
                  {(() => {
                    const quizScores = getQuizScores(selectedUser);
                    return quizScores.length > 0 ? (
                      <div className="quiz-scores">
                        {quizScores.slice(0, 5).map((quiz, index) => (
                          <div key={index} className="quiz-item">
                            <span>{quiz.courseName}</span>
                            <span className="quiz-score">{quiz.score}%</span>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <p>No quiz attempts</p>
                    );
                  })()}
                </div>
              </div>
            </div>
            
            <div className="modal-footer">
              <button 
                onClick={() => setShowModal(false)}
                className="btn-secondary"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AuditorDashboard;